### ISSUE TITLE
[1.16.5] Can't activate the rifts

### ISSUE THREAD

**Issue by MrHazMat** [jodlodi/BossRifts#2]
While testing around with mowzies mobs boss, killing them spawns a boss rift but player can't interact with it (no right-click animation), no visible border and just purple particle converging around the player.

**Comment by jodlodi** [comment]
Do you have a set spawn point? A bed, respawn anchor or anything similar from a mod? The Rifts won't work otherwise

**Comment by MrHazMat** [comment]
... I should have thought about that first, any plan on defaulting to world spawn?

**Comment by jodlodi** [comment]
Yea, maybe I should let players teleport to world spawn as well. I'll probably update the mod to let people do that

**Comment by jodlodi** [comment]
Implemented in 1.1 version
