### ISSUE TITLE
[1.18.1] Server Crashes on startup when attempting to load this mod

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [jodlodi/BossRifts#3]
Boss Rifts Version: 1.1
Minecraft Version: 1.18.1
Forge Version: 39.0.59
Crash Report: https://gist.github.com/NJL5390/83c71ffec8a01a5aabc1ae925930171e

Hello,
I've noticed that when attempting to get this mod working on my modded 1.18.1 server that the server just crashes when it attempts to load this mod, with the crash report shown above.

If I remove this mod then the server runs just fine.

I also just want to say that I love the concept of this mod and what it adds so thank you for making it!

**Comment by jodlodi** [comment]
Than you for reporting this! The issue has now been fixed, with the new files being up on CurseForge now. 
I apologize if it was a long wait, I was very sick, so I could not work on the mod. I hope you enjoy the mod.

**Comment by The-Bernician-Lamb** [comment]
No problem man, thanks for your help and have a good one!
